### ISSUE TITLE
BUG: Extension breaks user context menu

### ISSUE THREAD

**Issue by mq45946396** [KabirAcharya/MQEE#2]
When using the extension, the user context menu is  broken and only shows one option.

Without the extension the context menu looks like this:
![image](https://user-images.githubusercontent.com/53507048/118609209-ddc1b300-b7fd-11eb-9f52-bb417017b4fe.png)

However with the extension it instead looks like this:
![image](https://user-images.githubusercontent.com/53507048/118609328-f631cd80-b7fd-11eb-9c1b-e810c3be4bb9.png)

This should be fixed pretty urgently, as this makes the user unable to change preferences, switch roles or log out.

**Comment by KabirAcharya** [comment]
Urgent Hotfix Pushed v0.0.3-alpha KabirAcharya/MQEE@896cefd
