### ISSUE TITLE
BUG: Small logo

### ISSUE THREAD

**Issue by Romejanic** [KabirAcharya/MQEE#4]
In the current version the logo is incredibly small, to the point where it is illegible.

![original](https://user-images.githubusercontent.com/4233623/120586875-b0b90580-c477-11eb-8fdb-7cf720ecb3e8.png)

I fixed this issue in pull request #3, which produces this output:

![fix](https://user-images.githubusercontent.com/4233623/120586943-caf2e380-c477-11eb-9d1e-0bef287860b8.png)

Just letting you know so you can merge :)

**Comment by KabirAcharya** [comment]
Pulled #3 and fixed issue. Thanks!
